# Generated by Django 5.0.6 on 2024-07-23 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('acc_username', models.CharField(max_length=255, unique=True)),
                ('acc_password', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Reddit Accounts',
            },
        ),
        migrations.CreateModel(
            name='SubReddit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=255)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.redditaccounts')),
            ],
        ),
    ]
